### PR TITLE
fix windows unzip bug

### PR DESCRIPTION
**Pull request by luclu**
Fixes https://github.com/ethereum/mist/pull/1436#issuecomment-261919340
- [x] thorough testing

### CODE REVIEW

**Comment by hiddentao** [comment]
You forgot to update the code to use this new module :)

**Comment by luclu** [comment]
@hiddentao thanks Ram! I only updated it under mist's node_modules... :D
...amend and force pushed.

**Comment by luclu** [comment]
Works well now ;)
I will create another small PR later today, so please refrain from publishing yet!

**Comment by hiddentao** [comment]
Thanks!

**Pull request merged**
