### PR TITLE
fix 'fs.access' ghost error, remove obsolete 'fs.unlink'

### PR DESCRIPTION
**Pull request by luclu**
Eventually this step could be removed completely.

Ram, please feel free to publish a new version after merging these two - or should alex do now?! :)

### CODE REVIEW

**Comment by frozeman** [comment]
Shouldn't the unlink remove the old renamed file, or make sure that already existing dublicates get removed?

**Comment by hiddentao** [comment]
Yes I don't understand this change. It's supposed to remove the old link, that's why it does `unlink`. If `access` fails then there is no need to `unlink`.

**Comment by evertonfraga** [comment]
I implemented the `unlink` first place because I couldn't overwrite an alias (symlink), on windows only. Therefore, It had to be removed and created again.

**Comment by luclu** [comment]
AFAIK we don't use symlinking anymore as of this [commit](https://github.com/ethereum/ethereum-client-binaries/commit/baedbdd39a4c1ffe06fcf06dbb0587b8b71f6bc7) because it caused issues on windows.

Currently this will pollute the log on all platforms with:
```bash
[2016-11-23 14:20:28.271] [WARN] ClientBinaryManager - { Error: ENOENT: no such file or directory, access '/Users/ich/Library/Application Support/Mist/binaries/Geth/unpacked/geth'
    at Error (native)
    at Object.fs.accessSync (fs.js:248:11)
    at Object.fs.accessSync (ELECTRON_ASAR.js:420:27)
    at promise.then.e (/Users/ich/github/mist/node_modules/ethereum-client-binaries/src/index.js:350:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/Users/ich/Library/Application Support/Mist/binaries/Geth/unpacked/geth' }
```

**Comment by hiddentao** [comment]
Yeah but it copies the binary over, in which case erasing the existing binary first is a good idea just to make sure that the copy succeeds, unless we want to switch to copying with an overwrite. `fs.unlink` is how you delete files.

**Comment by luclu** [comment]
Ok, thank you guys for clarifying, I reverted it and modified the warning to not display if there is no file, like on the initial download.

**Review by frozeman — APPROVED** [review]

**Pull request merged**
