### PR TITLE
fix windows 32-bit bug

### PR DESCRIPTION
**Pull request by luclu**
Fixes https://github.com/ethereum/mist/issues/1318.

On Windows 32-bit (tested on win7) `command -v geth.exe` will evoke the `command.exe` / `cmd.exe`, thus `child_process.spawn` will open and lock up in a new shell.

To prevent this `where` can be used on windows systems to output the plain path.

- [x] thorough testing, will do tomorrow

Sorry for the trailing lines killer. Music is at [line 500](https://github.com/hiddentao/ethereum-client-binaries/pull/4/files#diff-1fdf421c05c1140f6d71444ea2b27638R500).

### CODE REVIEW

**Comment by luclu** [comment]
Tested on mac, linux64, win7-x64/ia32.

**Comment by hiddentao** [comment]
Thanks!

**Comment by hiddentao** [comment]
1.6.1 published

**Comment by luclu** [comment]
Awesome, thanks Ram!

**Pull request merged**
